apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teeswim-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AKAICH00/k8s-deployments.git
    targetRevision: main
    path: apps/teeswim-redis
  destination:
    server: https://kubernetes.default.svc
    namespace: teeswim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
