apiVersion: v1
kind: Service
metadata:
  name: teeswim-mockup
  namespace: teeswim
spec:
  type: ClusterIP
  selector:
    app: teeswim-mockup
  ports:
    - port: 8080
      targetPort: 8080
      name: http
