cluster_name: k3s-prod
location: fsn1
control_plane_server_type: cx41
agent_server_type: cx41
agent_count: 3
enable_public_ssh: false
enable_public_k8s_api: false
allowed_ssh_cidrs: []
allowed_k8s_api_cidrs: []
tailscale_authkey: "env:HETZNER_TS_AUTHKEY"
tailscale_tags:
  - tag:k8s
  - tag:prod
ssh_public_key_path: ~/.ssh/id_ed25519.pub
database_choice: postgres
starter_app: null
