apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: teeswim-secrets
  namespace: teeswim
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: teeswim-secrets
  config: prd
  project: teeswim
